// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Content struct {
	ID        int32     `json:"id"`
	Fileid    string    `json:"fileid"`
	Name      string    `json:"name"`
	Size      int64     `json:"size"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int32     `json:"id"`
	Username     string    `json:"username"`
	Password     string    `json:"password"`
	TokenRefresh string    `json:"tokenRefresh"`
	Status       bool      `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}
