// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	DeleteContent(ctx context.Context, id int32) error
	GetContent(ctx context.Context, id int32) (Content, error)
	GetContentUpdate(ctx context.Context, id int32) (Content, error)
	ListContents(ctx context.Context, arg ListContentsParams) ([]Content, error)
	UpdateContent(ctx context.Context, arg UpdateContentParams) (Content, error)
	createContent(ctx context.Context, arg createContentParams) (Content, error)
}

var _ Querier = (*Queries)(nil)
